import { ArrowRight, BookOpen, Code2, Eye, Radio, Trophy, Users } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { BrandMark } from '../components/BrandMark';
import { CodeEditorMock } from '../components/landing/CodeEditorMock';
import { TopBuildersCard } from '../components/landing/TopBuildersCard';
import { useReveal } from '../hooks/useReveal';

const features = [[Radio, 'Watch the thinking', 'Follow decisions, tradeoffs, and the messy middle of making something work.'], [Code2, 'Practice in the moment', 'Open the editor, test your ideas, and get immediate feedback while context is fresh.'], [Trophy, 'Compete & climb', 'Turn solved challenges into momentum on a leaderboard that rewards consistency.'], [Users, 'Grow together', 'Compare progress, celebrate wins, and learn from builders on the same path.']];

export function LandingPage() {
  const pageRef = useRef<HTMLDivElement>(null);
  const [scrolled, setScrolled] = useState(false);
  const [revealRoot, setRevealRoot] = useState<Element | null>(null);
  const scrollToSection = (event: React.MouseEvent<HTMLAnchorElement>, id: string) => { event.preventDefault(); const section = document.getElementById(id); const page = pageRef.current; if (section && page) page.scrollTo({ top: section.offsetTop - 24, behavior: 'smooth' }); window.history.replaceState(null, '', `#${id}`); };
  useEffect(() => { const page = pageRef.current; if (!page) return; setRevealRoot(page); const onScroll = () => setScrolled(page.scrollTop > 18); page.addEventListener('scroll', onScroll, { passive: true }); return () => page.removeEventListener('scroll', onScroll); }, []);
  const hero = useReveal<HTMLDivElement>(revealRoot); const feature = useReveal<HTMLElement>(revealRoot, 80); const how = useReveal<HTMLElement>(revealRoot, 120); const proof = useReveal<HTMLElement>(revealRoot, 160);
  return <div className="landing-page" ref={pageRef}><div className="landing-grid" />
    <header className={`landing-nav ${scrolled ? 'scrolled' : ''}`}><Link to="/" className="landing-brand"><img src="/icon.png" alt="DevCast" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = '/devcast-logo.png'; }} /><span>Dev<span>Cast</span></span></Link><nav><a href="#features" onClick={(e) => scrollToSection(e, 'features')}>Features</a><a href="#how-it-works" onClick={(e) => scrollToSection(e, 'how-it-works')}>How it works</a><a href="#community" onClick={(e) => scrollToSection(e, 'community')}>Community</a></nav><div className="landing-actions"><Link to="/login" className="landing-login">Log in</Link><Link to="/signup" className="button button-small">Get started <ArrowRight size={15} /></Link></div></header>
    <main><section className="landing-hero"><div className={`hero-copy reveal ${hero.inView ? 'in-view' : ''}`} ref={hero.ref} style={hero.style}><div className="landing-kicker"><span className="signal-dot" /> LIVE DEVELOPER NETWORK</div><h1>Build in public.<br /><em>Learn in motion.</em></h1><p>Watch real developers solve real problems, then open the editor and make the next move yourself.</p><div className="hero-actions"><Link to="/signup" className="button">Start building <ArrowRight size={18} /></Link><Link to="/live" className="text-link">Explore streams <Eye size={16} /></Link></div><div className="hero-proof"><span className="avatar-cluster"><i>m</i><i>s</i><i>l</i></span><span><strong>8,420+</strong> developers online</span><span className="watching"><strong>1,284</strong> watching now</span></div></div><div className="hero-art"><CodeEditorMock /><TopBuildersCard /><div className="challenge-chip"><BookOpen size={14} /> Challenge unlocked <b>+120 xp</b></div></div></section>
      <div className="language-marquee"><div>{['JavaScript', 'TypeScript', 'Python', 'C++', 'Go', 'Rust', 'Java', 'SQL'].map((language) => <span key={language}>{language}</span>)}</div></div>
      <section id="features" className="landing-section" ref={feature.ref}><div className={`reveal ${feature.inView ? 'in-view' : ''}`} style={feature.style}><div className="section-label">WHY DEVCAST</div><h2>The room is live. Your progress is real.</h2><p className="section-lede">DevCast brings the energy of a great workshop into your browser: a focused stream, a real challenge, and a community moving with you.</p></div><div className="feature-grid">{features.map(([Icon, title, text], index) => <article className={`feature-panel feature-${index + 1} reveal ${feature.inView ? 'in-view' : ''}`} style={{ '--reveal-delay': `${index * 90}ms` } as React.CSSProperties} key={title as string}><div className="feature-icon"><Icon size={19} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></section>
      <section id="how-it-works" className="landing-strip" ref={how.ref}><div className={`section-label reveal ${how.inView ? 'in-view' : ''}`} style={how.style}>HOW IT WORKS</div><div className="steps">{[['01', 'Join a live room', 'Find a session that matches your next question.'], ['02', 'Take the challenge', 'Turn watching into doing with a shared coding prompt.'], ['03', 'Climb the leaderboard', 'Keep your streak and your curiosity moving.']].map(([number, title, text]) => <div className="step" key={number}><span className="step-number">{number}</span><strong>{title}</strong><p>{text}</p></div>)}</div></section>
      <section id="community" className="community-section" ref={proof.ref}><div className={`section-heading-row reveal ${proof.inView ? 'in-view' : ''}`} style={proof.style}><div><div className="section-label">COMMUNITY SIGNAL</div><h2>Top builders this week.</h2></div><Link to="/leaderboards" className="text-link">See leaderboard <ArrowRight size={15} /></Link></div><div className="stats-band"><span><strong>8,420+</strong> developers online</span><span><strong>24/7</strong> live practice</span><span><strong>18,642</strong> challenges solved</span></div></section>
      <section className="final-cta"><div><div className="section-label">YOUR NEXT SESSION STARTS HERE</div><h2>Start building in public.</h2><p>Bring a question. Leave with momentum.</p></div><div className="hero-actions"><Link to="/signup" className="button">Get started <ArrowRight size={18} /></Link><Link to="/login" className="text-link">I have an account</Link></div></section></main>
    <footer className="landing-footer"><Link to="/" className="landing-brand"><BrandMark size={28} /><span>Dev<span>Cast</span></span></Link><span>Live coding. Real learning.</span><div><Link to="/login">Log in</Link><Link to="/signup">Sign up</Link></div></footer></div>;
}
